version: '3.8'
services:
  app:
    container_name: shalotts_app
    build:
      context: .
      dockerfile: ./docker/sha/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    networks:
      - shalotts
    environment:
      - NODE_ENV=production
      - LOG_LVL=info
      - HOST=localhost
      - PORT=3000
    volumes:
      - ./:/usr/src/app
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 200M

networks:
  shalotts: