[build]
publish = "dist/client/"
command = "bun install && bun run vite build"

[functions]
directory = "/app/module/adapter/netlify/functions"

[[redirects]]
from = "/*"
to = "/app/module/adapter/netlify/functions/index.ts"
status = 200
